name: Deploy Chatapp to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Chatapp to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/chatapp
            git pull origin main

            cd backend
            npm install

            cd ../frontend
            npm install
            npm run build

            pm2 restart chatapp-backend || pm2 start ../backend/src/index.js --name chatapp-backend
            pm2 save
